# The Site Configuration

# theme: minima
# theme: career-archive
baseurl: ""
url: "https://jiunkoo.github.io/"

title: Koubit's Career Archive
description: >-
  A career archive for storing resumes, cover letters, and portfolios.

email: jiunkoo0106@gmail.com

github:
  username: jiunkoo

plugins:
  - jekyll-feed

data_path: data

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
