# The Site Configuration

# theme: minima
# theme: career-archive
url: "https://jiunkoo.github.io"
baseurl: ""

title: Koubit's Career Archive
description: >-
  A career archive for storing resumes, cover letters, and portfolios.

email: jiunkoo0106@gmail.com

github:
  username: jiunkoo

plugins:
  - jekyll-feed

data_path: data

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

css:
  /career
